spring:
  application:
    name: monito

  profiles:
    active: dev

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}  # ?? 32? ??
    expiration: 86400000  # 24?? (???)
    refresh-expiration: 604800000  # 7? (???)