spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        default_batch_fetch_size: 100
        generate_statistics: false
    show-sql: false

server:
  port: 8081