-- 모든 시퀀스 생성
CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AGENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONTAINER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONTAINER_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONTAINER_STATS_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALERT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALERT_RULE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DASHBOARD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DASHBOARD_WIDGET_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE WIDGET_TEMPLATE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FAVORITE_SEQ START WITH 1 INCREMENT BY 1;